import {
  ALL_TEN_STAT_CAPS,
  BODY_ONLY_SMASHER_CAPS,
  type ProjectileProfile,
  type TankAbility,
  type TankClassDefinition,
  type WeaponMount,
} from './tankTypes';

const bullet: ProjectileProfile = {
  kind: 'bullet',
  speed: 620,
  damage: 18,
  penetration: 28,
  radius: 8,
  lifetimeMs: 1150,
};

const miniBullet: ProjectileProfile = {
  kind: 'bullet',
  speed: 690,
  damage: 8,
  penetration: 14,
  radius: 5,
  lifetimeMs: 900,
};

const heavyBullet: ProjectileProfile = {
  kind: 'bullet',
  speed: 470,
  damage: 82,
  penetration: 140,
  radius: 18,
  lifetimeMs: 1350,
};

const trap: ProjectileProfile = {
  kind: 'trap',
  speed: 360,
  damage: 34,
  penetration: 90,
  radius: 12,
  lifetimeMs: 5200,
  dampingAfterMs: 850,
};

const drone: ProjectileProfile = {
  kind: 'drone',
  speed: 360,
  damage: 18,
  penetration: 42,
  radius: 9,
  lifetimeMs: 9000,
  turnRate: 7,
};

const minion: ProjectileProfile = {
  kind: 'minion',
  speed: 300,
  damage: 15,
  penetration: 60,
  radius: 12,
  lifetimeMs: 11000,
  turnRate: 5,
};

const missile: ProjectileProfile = {
  kind: 'missile',
  speed: 420,
  damage: 58,
  penetration: 110,
  radius: 14,
  lifetimeMs: 1650,
  turnRate: 2.4,
};

interface WeaponOptions {
  angleDeg?: number;
  reloadMs?: number;
  projectile?: ProjectileProfile;
  length?: number;
  width?: number;
  offset?: number;
  spreadDeg?: number;
  recoil?: number;
  damageScale?: number;
  speedScale?: number;
  sizeScale?: number;
  lifetimeScale?: number;
  autoAim?: boolean;
  altFire?: boolean;
  staggerMs?: number;
}

function w(id: string, options: WeaponOptions = {}): WeaponMount {
  return {
    id,
    angleDeg: options.angleDeg ?? 0,
    reloadMs: options.reloadMs ?? 560,
    projectile: options.projectile ?? bullet,
    length: options.length ?? 44,
    width: options.width ?? 17,
    offset: options.offset ?? 25,
    spreadDeg: options.spreadDeg,
    recoil: options.recoil ?? 32,
    damageScale: options.damageScale,
    speedScale: options.speedScale,
    sizeScale: options.sizeScale,
    lifetimeScale: options.lifetimeScale,
    autoAim: options.autoAim,
    altFire: options.altFire,
    staggerMs: options.staggerMs,
  };
}

function spread(prefix: string, angles: number[], options: WeaponOptions = {}): WeaponMount[] {
  return angles.map((angleDeg, index) => w(`${prefix}-${index + 1}`, { ...options, angleDeg }));
}

function auto(prefix: string, angles: number[], options: WeaponOptions = {}): WeaponMount[] {
  return spread(prefix, angles, {
    projectile: miniBullet,
    reloadMs: 680,
    length: 30,
    width: 12,
    offset: 19,
    recoil: 6,
    ...options,
    autoAim: true,
  });
}

function tank(definition: TankClassDefinition): TankClassDefinition {
  return definition;
}

const noWeapons: WeaponMount[] = [];

export const TANK_CLASSES: TankClassDefinition[] = [
  tank({
    id: 'basic',
    displayName: 'Basic',
    tier: 1,
    unlockLevel: 1,
    parents: [],
    weaponLayout: [w('main')],
    abilities: [],
    tags: ['starter', 'bullet'],
  }),
  tank({
    id: 'twin',
    displayName: 'Twin',
    tier: 2,
    unlockLevel: 15,
    parents: ['basic'],
    weaponLayout: spread('twin', [-5, 5], { reloadMs: 500, damageScale: 0.78, recoil: 22 }),
    abilities: [],
    tags: ['bullet', 'multi-barrel'],
  }),
  tank({
    id: 'sniper',
    displayName: 'Sniper',
    tier: 2,
    unlockLevel: 15,
    parents: ['basic'],
    weaponLayout: [w('sniper', { reloadMs: 860, speedScale: 1.35, lifetimeScale: 1.35, recoil: 18 })],
    abilities: [],
    tags: ['bullet', 'range'],
    fovMultiplier: 1.14,
  }),
  tank({
    id: 'machine_gun',
    displayName: 'Machine Gun',
    tier: 2,
    unlockLevel: 15,
    parents: ['basic'],
    weaponLayout: [w('spray', { reloadMs: 270, spreadDeg: 10, damageScale: 0.72, recoil: 24, width: 24 })],
    abilities: [],
    tags: ['bullet', 'spray'],
  }),
  tank({
    id: 'flank_guard',
    displayName: 'Flank Guard',
    tier: 2,
    unlockLevel: 15,
    parents: ['basic'],
    weaponLayout: spread('flank', [0, 180], { reloadMs: 560, recoil: 18 }),
    abilities: [],
    tags: ['bullet', 'flank'],
  }),
  tank({
    id: 'triple_shot',
    displayName: 'Triple Shot',
    tier: 3,
    unlockLevel: 30,
    parents: ['twin'],
    weaponLayout: spread('triple-shot', [-18, 0, 18], { reloadMs: 560, damageScale: 0.68, recoil: 18 }),
    abilities: [],
    tags: ['bullet', 'spread'],
  }),
  tank({
    id: 'quad_tank',
    displayName: 'Quad Tank',
    tier: 3,
    unlockLevel: 30,
    parents: ['twin', 'flank_guard'],
    weaponLayout: spread('quad', [0, 90, 180, 270], { reloadMs: 620, damageScale: 0.72, recoil: 0 }),
    abilities: ['auto-spin-friendly'],
    tags: ['bullet', 'radial'],
  }),
  tank({
    id: 'twin_flank',
    displayName: 'Twin Flank',
    tier: 3,
    unlockLevel: 30,
    parents: ['twin', 'flank_guard'],
    weaponLayout: spread('twin-flank', [-5, 5, 175, 185], { reloadMs: 560, damageScale: 0.68, recoil: 0 }),
    abilities: [],
    tags: ['bullet', 'flank'],
  }),
  tank({
    id: 'assassin',
    displayName: 'Assassin',
    tier: 3,
    unlockLevel: 30,
    parents: ['sniper'],
    weaponLayout: [w('assassin', { reloadMs: 1040, speedScale: 1.48, lifetimeScale: 1.55, recoil: 15 })],
    abilities: [],
    tags: ['bullet', 'range'],
    fovMultiplier: 1.28,
  }),
  tank({
    id: 'overseer',
    displayName: 'Overseer',
    tier: 3,
    unlockLevel: 30,
    parents: ['sniper'],
    weaponLayout: spread('overseer', [-18, 18], {
      projectile: drone,
      reloadMs: 850,
      length: 30,
      width: 17,
      offset: 22,
      recoil: 0,
    }),
    abilities: ['drone-control'],
    tags: ['drone'],
    maxDrones: 8,
    fovMultiplier: 1.08,
  }),
  tank({
    id: 'hunter',
    displayName: 'Hunter',
    tier: 3,
    unlockLevel: 30,
    parents: ['sniper'],
    weaponLayout: [
      w('hunter-heavy', { reloadMs: 940, speedScale: 1.26, damageScale: 1.05, lifetimeScale: 1.25 }),
      w('hunter-small', { reloadMs: 940, projectile: miniBullet, speedScale: 1.38, staggerMs: 90, recoil: 8 }),
    ],
    abilities: ['burst-fire'],
    tags: ['bullet', 'range', 'burst'],
    fovMultiplier: 1.18,
  }),
  tank({
    id: 'trapper',
    displayName: 'Trapper',
    tier: 3,
    unlockLevel: 30,
    parents: ['sniper'],
    weaponLayout: [w('trapper', { projectile: trap, reloadMs: 780, length: 34, width: 24, recoil: 6 })],
    abilities: ['trap-launcher'],
    tags: ['trap', 'defense'],
    fovMultiplier: 1.08,
  }),
  tank({
    id: 'destroyer',
    displayName: 'Destroyer',
    tier: 3,
    unlockLevel: 30,
    parents: ['machine_gun'],
    weaponLayout: [w('destroyer', { projectile: heavyBullet, reloadMs: 1380, length: 50, width: 31, recoil: 70 })],
    abilities: [],
    tags: ['bullet', 'heavy'],
  }),
  tank({
    id: 'gunner',
    displayName: 'Gunner',
    tier: 3,
    unlockLevel: 30,
    parents: ['machine_gun'],
    weaponLayout: spread('gunner', [-6, -2, 2, 6], {
      projectile: miniBullet,
      reloadMs: 220,
      damageScale: 0.78,
      recoil: 5,
      width: 8,
      length: 34,
    }),
    abilities: [],
    tags: ['bullet', 'stream'],
  }),
  tank({
    id: 'shotgun',
    displayName: 'Shotgun',
    tier: 3,
    unlockLevel: 30,
    parents: ['machine_gun'],
    weaponLayout: spread('shotgun', [-20, -14, -9, -5, -2, 2, 5, 9, 14, 20], {
      projectile: miniBullet,
      reloadMs: 980,
      speedScale: 1.08,
      damageScale: 0.65,
      lifetimeScale: 0.65,
      recoil: 55,
    }),
    abilities: ['burst-fire'],
    tags: ['bullet', 'shotgun'],
  }),
  tank({
    id: 'tri_angle',
    displayName: 'Tri-Angle',
    tier: 3,
    unlockLevel: 30,
    parents: ['flank_guard'],
    weaponLayout: [
      w('tri-front', { reloadMs: 520, recoil: 20 }),
      ...spread('tri-rear', [145, 215], { reloadMs: 520, damageScale: 0.25, recoil: 48, width: 13 }),
    ],
    abilities: [],
    tags: ['bullet', 'recoil-move'],
  }),
  tank({
    id: 'auto_3',
    displayName: 'Auto 3',
    tier: 3,
    unlockLevel: 30,
    parents: ['flank_guard'],
    weaponLayout: auto('auto3', [0, 120, 240], { reloadMs: 560 }),
    abilities: ['auto-turret', 'auto-spin-friendly'],
    tags: ['auto', 'bullet'],
  }),
  tank({
    id: 'smasher',
    displayName: 'Smasher',
    tier: 3,
    unlockLevel: 30,
    parents: ['basic'],
    requiresSkippedUpgrade: true,
    weaponLayout: noWeapons,
    abilities: ['rammer'],
    tags: ['rammer'],
    statCaps: BODY_ONLY_SMASHER_CAPS,
    bodyRadius: 27,
    bodyShape: 'hex',
    fovMultiplier: 1.14,
  }),
  tank({
    id: 'triplet',
    displayName: 'Triplet',
    tier: 4,
    unlockLevel: 45,
    parents: ['triple_shot'],
    weaponLayout: spread('triplet', [-7, 0, 7], { reloadMs: 320, damageScale: 0.72, recoil: 18 }),
    abilities: [],
    tags: ['bullet', 'stream'],
  }),
  tank({
    id: 'penta_shot',
    displayName: 'Penta Shot',
    tier: 4,
    unlockLevel: 45,
    parents: ['triple_shot'],
    weaponLayout: spread('penta', [-28, -14, 0, 14, 28], { reloadMs: 470, damageScale: 0.6, recoil: 24 }),
    abilities: [],
    tags: ['bullet', 'spread'],
  }),
  tank({
    id: 'spread_shot',
    displayName: 'Spread Shot',
    tier: 4,
    unlockLevel: 45,
    parents: ['triple_shot'],
    weaponLayout: [
      w('spread-center', { reloadMs: 660, damageScale: 0.95, recoil: 4 }),
      ...spread('spread-mini', [-42, -34, -26, -18, -10, 10, 18, 26, 34, 42], {
        projectile: miniBullet,
        reloadMs: 660,
        damageScale: 0.65,
        recoil: 0,
        width: 8,
      }),
    ],
    abilities: [],
    tags: ['bullet', 'spread'],
  }),
  tank({
    id: 'octo_tank',
    displayName: 'Octo Tank',
    tier: 4,
    unlockLevel: 45,
    parents: ['quad_tank'],
    weaponLayout: spread('octo', [0, 45, 90, 135, 180, 225, 270, 315], {
      reloadMs: 620,
      damageScale: 0.64,
      recoil: 0,
    }),
    abilities: ['auto-spin-friendly'],
    tags: ['bullet', 'radial'],
  }),
  tank({
    id: 'auto_5',
    displayName: 'Auto 5',
    tier: 4,
    unlockLevel: 45,
    parents: ['quad_tank', 'auto_3'],
    weaponLayout: auto('auto5', [0, 72, 144, 216, 288], { reloadMs: 520 }),
    abilities: ['auto-turret', 'auto-spin-friendly'],
    tags: ['auto', 'bullet'],
  }),
  tank({
    id: 'triple_twin',
    displayName: 'Triple Twin',
    tier: 4,
    unlockLevel: 45,
    parents: ['twin_flank'],
    weaponLayout: spread('triple-twin', [-5, 5, 115, 125, 235, 245], {
      reloadMs: 520,
      damageScale: 0.7,
      recoil: 0,
    }),
    abilities: ['auto-spin-friendly'],
    tags: ['bullet', 'radial'],
  }),
  tank({
    id: 'battleship',
    displayName: 'Battleship',
    tier: 4,
    unlockLevel: 45,
    parents: ['twin_flank', 'overseer'],
    weaponLayout: spread('battleship', [-32, -12, 12, 32], {
      projectile: drone,
      reloadMs: 360,
      damageScale: 0.7,
      lifetimeScale: 0.45,
      width: 13,
      length: 25,
      recoil: 0,
    }),
    abilities: ['drone-control'],
    tags: ['drone', 'swarm'],
    maxDrones: 14,
  }),
  tank({
    id: 'ranger',
    displayName: 'Ranger',
    tier: 4,
    unlockLevel: 45,
    parents: ['assassin'],
    weaponLayout: [w('ranger', { reloadMs: 1180, speedScale: 1.65, lifetimeScale: 1.78, recoil: 12 })],
    abilities: [],
    tags: ['bullet', 'range'],
    fovMultiplier: 1.45,
  }),
  tank({
    id: 'stalker',
    displayName: 'Stalker',
    tier: 4,
    unlockLevel: 45,
    parents: ['assassin'],
    weaponLayout: [w('stalker', { reloadMs: 1080, speedScale: 1.45, lifetimeScale: 1.45, recoil: 12 })],
    abilities: ['invisibility'],
    tags: ['bullet', 'stealth'],
    fovMultiplier: 1.28,
  }),
  tank({
    id: 'overlord',
    displayName: 'Overlord',
    tier: 4,
    unlockLevel: 45,
    parents: ['overseer'],
    weaponLayout: spread('overlord', [-35, -12, 12, 35], {
      projectile: drone,
      reloadMs: 760,
      length: 30,
      width: 17,
      recoil: 0,
    }),
    abilities: ['drone-control'],
    tags: ['drone'],
    maxDrones: 8,
    fovMultiplier: 1.08,
  }),
  tank({
    id: 'necromancer',
    displayName: 'Necromancer',
    tier: 4,
    unlockLevel: 45,
    parents: ['overseer'],
    weaponLayout: spread('necromancer', [-18, 18], {
      projectile: drone,
      reloadMs: 520,
      damageScale: 0.72,
      width: 15,
      recoil: 0,
    }),
    abilities: ['drone-control'],
    tags: ['drone', 'swarm'],
    maxDrones: 24,
    bodyShape: 'square',
  }),
  tank({
    id: 'manager',
    displayName: 'Manager',
    tier: 4,
    unlockLevel: 45,
    parents: ['overseer'],
    weaponLayout: [w('manager', { projectile: drone, reloadMs: 420, length: 30, width: 17, recoil: 0 })],
    abilities: ['drone-control', 'invisibility'],
    tags: ['drone', 'stealth'],
    maxDrones: 8,
  }),
  tank({
    id: 'overtrapper',
    displayName: 'Overtrapper',
    tier: 4,
    unlockLevel: 45,
    parents: ['overseer', 'trapper'],
    weaponLayout: [
      w('overtrap-main', { projectile: trap, reloadMs: 850, length: 34, width: 22, recoil: 4 }),
      ...spread('overtrap-drone', [-26, 26], { projectile: drone, reloadMs: 980, damageScale: 0.75, recoil: 0 }),
    ],
    abilities: ['trap-launcher', 'drone-control'],
    tags: ['trap', 'drone'],
    maxDrones: 4,
  }),
  tank({
    id: 'factory',
    displayName: 'Factory',
    tier: 4,
    unlockLevel: 45,
    parents: ['overseer'],
    weaponLayout: spread('factory', [-16, 16], {
      projectile: minion,
      reloadMs: 900,
      length: 33,
      width: 18,
      recoil: 0,
    }),
    abilities: ['factory-minions', 'drone-control'],
    tags: ['minion'],
    maxDrones: 6,
    bodyShape: 'square',
  }),
  tank({
    id: 'predator',
    displayName: 'Predator',
    tier: 4,
    unlockLevel: 45,
    parents: ['hunter'],
    weaponLayout: [
      w('pred-heavy', { reloadMs: 1020, speedScale: 1.35, damageScale: 1.08, lifetimeScale: 1.35 }),
      w('pred-mid', { reloadMs: 1020, projectile: miniBullet, speedScale: 1.45, staggerMs: 80, recoil: 7 }),
      w('pred-top', { reloadMs: 1020, projectile: miniBullet, speedScale: 1.5, staggerMs: 150, recoil: 7 }),
    ],
    abilities: ['burst-fire', 'predator-focus'],
    tags: ['bullet', 'range', 'focus'],
    fovMultiplier: 1.22,
  }),
  tank({
    id: 'streamliner',
    displayName: 'Streamliner',
    tier: 4,
    unlockLevel: 45,
    parents: ['hunter', 'gunner'],
    weaponLayout: spread('streamliner', [-2, -1, 0, 1, 2], {
      projectile: miniBullet,
      reloadMs: 125,
      damageScale: 0.62,
      speedScale: 1.14,
      recoil: 4,
      staggerMs: 35,
      width: 8,
    }),
    abilities: ['burst-fire'],
    tags: ['bullet', 'stream'],
    fovMultiplier: 1.15,
  }),
  tank({
    id: 'tri_trapper',
    displayName: 'Tri-Trapper',
    tier: 4,
    unlockLevel: 45,
    parents: ['trapper'],
    weaponLayout: spread('tri-trap', [0, 120, 240], {
      projectile: trap,
      reloadMs: 620,
      lifetimeScale: 0.72,
      recoil: 0,
    }),
    abilities: ['trap-launcher'],
    tags: ['trap', 'radial'],
  }),
  tank({
    id: 'gunner_trapper',
    displayName: 'Gunner Trapper',
    tier: 4,
    unlockLevel: 45,
    parents: ['trapper', 'gunner'],
    weaponLayout: [
      ...spread('gt-gun', [-4, 4], { projectile: miniBullet, reloadMs: 230, damageScale: 0.7, recoil: 5, width: 8 }),
      w('gt-trap', { projectile: trap, angleDeg: 180, reloadMs: 780, length: 30, width: 19, recoil: 0 }),
    ],
    abilities: ['trap-launcher'],
    tags: ['trap', 'bullet'],
  }),
  tank({
    id: 'mega_trapper',
    displayName: 'Mega Trapper',
    tier: 4,
    unlockLevel: 45,
    parents: ['trapper'],
    weaponLayout: [w('mega-trap', { projectile: trap, reloadMs: 1120, sizeScale: 1.55, damageScale: 1.75, length: 42, width: 32 })],
    abilities: ['trap-launcher'],
    tags: ['trap', 'heavy'],
  }),
  tank({
    id: 'auto_trapper',
    displayName: 'Auto Trapper',
    tier: 4,
    unlockLevel: 45,
    parents: ['trapper'],
    weaponLayout: [
      w('auto-trap', { projectile: trap, reloadMs: 820, length: 34, width: 22, recoil: 4 }),
      ...auto('auto-trap-turret', [0], { reloadMs: 560, offset: 8 }),
    ],
    abilities: ['trap-launcher', 'auto-turret'],
    tags: ['trap', 'auto'],
  }),
  tank({
    id: 'hybrid',
    displayName: 'Hybrid',
    tier: 4,
    unlockLevel: 45,
    parents: ['destroyer'],
    weaponLayout: [
      w('hybrid-heavy', { projectile: heavyBullet, reloadMs: 1380, length: 50, width: 31, recoil: 68 }),
      w('hybrid-drone', { projectile: drone, angleDeg: 180, reloadMs: 1300, damageScale: 0.8, recoil: 0 }),
    ],
    abilities: ['drone-control'],
    tags: ['heavy', 'drone'],
    maxDrones: 2,
  }),
  tank({
    id: 'annihilator',
    displayName: 'Annihilator',
    tier: 4,
    unlockLevel: 45,
    parents: ['destroyer'],
    weaponLayout: [w('annihilator', { projectile: heavyBullet, reloadMs: 1450, sizeScale: 1.22, damageScale: 1.25, recoil: 88, width: 36 })],
    abilities: [],
    tags: ['heavy'],
  }),
  tank({
    id: 'skimmer',
    displayName: 'Skimmer',
    tier: 4,
    unlockLevel: 45,
    parents: ['destroyer'],
    weaponLayout: [w('skimmer', { projectile: missile, reloadMs: 1180, recoil: 55, width: 28 })],
    abilities: [],
    tags: ['missile', 'heavy'],
  }),
  tank({
    id: 'rocketeer',
    displayName: 'Rocketeer',
    tier: 4,
    unlockLevel: 45,
    parents: ['destroyer'],
    weaponLayout: [w('rocketeer', { projectile: missile, reloadMs: 1320, damageScale: 1.12, speedScale: 1.1, recoil: 62, width: 30 })],
    abilities: [],
    tags: ['missile', 'heavy'],
  }),
  tank({
    id: 'glider',
    displayName: 'Glider',
    tier: 4,
    unlockLevel: 45,
    parents: ['destroyer'],
    weaponLayout: [w('glider', { projectile: missile, reloadMs: 1240, speedScale: 1.05, recoil: 58, width: 28 })],
    abilities: [],
    tags: ['missile'],
  } as TankClassDefinition),
  tank({
    id: 'firework',
    displayName: 'Firework',
    tier: 4,
    unlockLevel: 45,
    parents: ['destroyer'],
    weaponLayout: [w('firework', { projectile: { ...missile, splitCount: 12 }, reloadMs: 1400, recoil: 58, width: 28 })],
    abilities: [],
    tags: ['missile', 'burst'],
  }),
  tank({
    id: 'auto_gunner',
    displayName: 'Auto Gunner',
    tier: 4,
    unlockLevel: 45,
    parents: ['gunner', 'auto_3'],
    weaponLayout: [
      ...spread('auto-gunner-main', [-6, -2, 2, 6], { projectile: miniBullet, reloadMs: 230, recoil: 4, width: 8 }),
      ...auto('auto-gunner-turret', [0], { reloadMs: 520, offset: 8 }),
    ],
    abilities: ['auto-turret'],
    tags: ['bullet', 'auto'],
  }),
  tank({
    id: 'pellet_shot',
    displayName: 'Pellet Shot',
    tier: 4,
    unlockLevel: 45,
    parents: ['shotgun'],
    weaponLayout: spread(
      'pellet',
      [-30, -25, -20, -16, -12, -8, -4, 0, 4, 8, 12, 16, 20, 25, 30],
      { projectile: miniBullet, reloadMs: 1060, damageScale: 0.55, lifetimeScale: 0.72, recoil: 62 },
    ),
    abilities: ['burst-fire'],
    tags: ['bullet', 'shotgun'],
    fovMultiplier: 1.08,
  }),
  tank({
    id: 'dual_barrel',
    displayName: 'Dual-Barrel',
    tier: 4,
    unlockLevel: 45,
    parents: ['shotgun'],
    weaponLayout: [
      ...spread('dual-main', [-16, -8, 0, 8, 16], { projectile: miniBullet, reloadMs: 850, lifetimeScale: 0.72, recoil: 32 }),
      ...spread('dual-alt', [-16, -8, 0, 8, 16], {
        projectile: miniBullet,
        reloadMs: 850,
        lifetimeScale: 0.72,
        recoil: 32,
        altFire: true,
        angleDeg: 0,
      }),
    ],
    abilities: ['burst-fire'],
    tags: ['bullet', 'shotgun', 'alt-fire'],
  }),
  tank({
    id: 'sprayer',
    displayName: 'Sprayer',
    tier: 4,
    unlockLevel: 45,
    parents: ['machine_gun'],
    requiresSkippedUpgrade: true,
    weaponLayout: [
      w('sprayer-main', { reloadMs: 240, spreadDeg: 8, damageScale: 0.74, recoil: 24, width: 24 }),
      w('sprayer-needle', { projectile: miniBullet, reloadMs: 150, spreadDeg: 2, damageScale: 0.32, recoil: 3, width: 8 }),
    ],
    abilities: [],
    tags: ['bullet', 'spray'],
  }),
  tank({
    id: 'booster',
    displayName: 'Booster',
    tier: 4,
    unlockLevel: 45,
    parents: ['tri_angle'],
    weaponLayout: [
      w('booster-front', { reloadMs: 500, recoil: 18 }),
      ...spread('booster-rear', [136, 158, 202, 224], { reloadMs: 500, damageScale: 0.22, recoil: 42, width: 12 }),
    ],
    abilities: [],
    tags: ['bullet', 'recoil-move'],
  }),
  tank({
    id: 'fighter',
    displayName: 'Fighter',
    tier: 4,
    unlockLevel: 45,
    parents: ['tri_angle'],
    weaponLayout: [
      w('fighter-front', { reloadMs: 480, recoil: 18 }),
      ...spread('fighter-rear', [145, 215], { reloadMs: 480, damageScale: 0.24, recoil: 40, width: 12 }),
      ...spread('fighter-side', [80, 280], { reloadMs: 560, damageScale: 0.48, recoil: 0, width: 12 }),
    ],
    abilities: [],
    tags: ['bullet', 'recoil-move'],
  }),
  tank({
    id: 'landmine',
    displayName: 'Landmine',
    tier: 4,
    unlockLevel: 45,
    parents: ['smasher'],
    weaponLayout: noWeapons,
    abilities: ['rammer', 'invisibility'],
    tags: ['rammer', 'stealth'],
    statCaps: BODY_ONLY_SMASHER_CAPS,
    bodyRadius: 28,
    bodyShape: 'hex',
  }),
  tank({
    id: 'auto_smasher',
    displayName: 'Auto Smasher',
    tier: 4,
    unlockLevel: 45,
    parents: ['smasher'],
    weaponLayout: auto('auto-smasher', [0], { reloadMs: 610, offset: 8 }),
    abilities: ['rammer', 'auto-turret'],
    tags: ['rammer', 'auto'],
    statCaps: ALL_TEN_STAT_CAPS,
    bodyRadius: 28,
    bodyShape: 'hex',
  }),
  tank({
    id: 'spike',
    displayName: 'Spike',
    tier: 4,
    unlockLevel: 45,
    parents: ['smasher'],
    weaponLayout: noWeapons,
    abilities: ['rammer'],
    tags: ['rammer'],
    statCaps: BODY_ONLY_SMASHER_CAPS,
    bodyRadius: 31,
    bodyShape: 'spiked',
  }),
  tank({
    id: 'auto_tank',
    displayName: 'Auto Tank',
    tier: 4,
    unlockLevel: 45,
    parents: ['basic'],
    requiresSkippedUpgrade: true,
    weaponLayout: [w('auto-tank-main'), ...auto('auto-tank-turret', [0], { reloadMs: 620, offset: 8 })],
    abilities: ['auto-turret'],
    tags: ['bullet', 'auto'],
  }),
];

export const TANK_CLASSES_BY_ID = Object.fromEntries(TANK_CLASSES.map((tankClass) => [tankClass.id, tankClass])) as Record<
  string,
  TankClassDefinition
>;

export const BASELINE_TANK_COUNT = 54;

export const BASELINE_TANK_SOURCE_NOTE =
  'Baseline tree seeded from the public Diep.io wiki Tiers page current normal tanks; removed, event, and special tanks are intentionally excluded.';

export function getTankClass(id: string): TankClassDefinition {
  return TANK_CLASSES_BY_ID[id] ?? TANK_CLASSES_BY_ID.basic;
}

export function hasAbility(tankId: string, ability: TankAbility): boolean {
  return getTankClass(tankId).abilities.includes(ability);
}
